name: paginated_listview
description: A simple ListView to handle pagination to your API queries or whatever you want to do :)
version: 0.0.1+2
maintainer: Miguel Vega (@atleugim)
homepage: https://github.com/atleugim/flutter-paginated_listview

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
